Fix build error caused by upstream code changes
```
common/net.go:46:16: too many arguments in call to sess.Close
have (error)
want ()
common/net.go:105:16: too many arguments in call to qd.sess.Close
have (error)
want ()
```